#!/bin/bash

DOCKER_NAME="ikev2-vpn-xauth"

echo "Stopping container..."
docker stop ${DOCKER_NAME}

echo "Removing old container..."
docker rm ${DOCKER_NAME}

echo "Rebuilding from local Dockerfile..."
docker build -t azmenak/${DOCKER_NAME} .

echo "Create new Docker container..."
docker run -d --name ${DOCKER_NAME} --privileged -p 500:500/udp -p 4500:4500/udp azmenak/${DOCKER_NAME}

echo "Shared Secret:"
docker exec ${DOCKER_NAME} cat /etc/ipsec.secrets | sed 's/.*"\(.*\)"/\1/g' | head -n 1

